version: '3.9'


services:
# MongoDB service

mongo_db:
   container_name: db_container
   image: mongo:latest
   restart: always 
   volumes:
    - mongo_db:/data/db

# # Node API service
#     api:
#       build: .
#       ports:
#          - 8000:3000
      